spring:
  application:
    name: jhand

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:5432/JHand
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
    max-part-count: 1000