package com.gui.jhand.action;

public enum ActionType {

	HEADER, TABLE_INFO, SEAT_INFO, POST_ANTE, POST_BLIND, DEALT_TO_HERO, ACTION_FOLD, ACTION_CALL, ACTION_RAISE,
	ACTION_BET, ACTION_CHECK, FLOP_CARDS, TURN_CARDS, RIVER_CARDS, UNCALLED_BET_RETURNED, SHOWDOWN_HEADER, CARDS_SHOWN,
	COLLECTED_POT, SUMMARY_HEADER, TOTAL_POT, BOARD, SEAT_HAND_RESULT

}
